"""
stock_cache.py — local CSV fallback for the Lynch Stock Analyzer.

Priority order for each ticker:
  1. cache/{ticker}_enriched.csv  — OHLCV + all ten financial metrics
     (generated by enrich_cache.py via SEC EDGAR)
  2. cache/{ticker}_hist.csv      — raw OHLCV only; metrics will be None

When the Yahoo Finance API is unavailable this module provides the same
dict structure that fetch_fundamentals() returns and the same DataFrame
that fetch_history() returns, so app.py renders without modification.
"""

from pathlib import Path
import numpy as np
import pandas as pd

CACHE_DIR = Path(__file__).parent / "cache"

# Static metadata: name / sector / industry / description cannot be read
# from an OHLCV CSV, so they are kept here for the 10 cached tickers.
_META: dict[str, dict] = {
    "AAPL": {
        "name": "Apple Inc.",
        "sector": "Technology",
        "industry": "Consumer Electronics",
        "description": (
            "Apple Inc. designs, manufactures, and markets smartphones, personal "
            "computers, tablets, wearables, and accessories worldwide."
        ),
    },
    "AMZN": {
        "name": "Amazon.com, Inc.",
        "sector": "Consumer Cyclical",
        "industry": "Internet Retail",
        "description": (
            "Amazon.com operates as a technology company offering e-commerce, cloud "
            "computing (AWS), digital streaming, and artificial intelligence services."
        ),
    },
    "META": {
        "name": "Meta Platforms, Inc.",
        "sector": "Communication Services",
        "industry": "Internet Content & Information",
        "description": (
            "Meta develops products that enable people to connect and share via "
            "Facebook, Instagram, WhatsApp, and immersive Reality Labs technologies."
        ),
    },
    "MSFT": {
        "name": "Microsoft Corporation",
        "sector": "Technology",
        "industry": "Software - Infrastructure",
        "description": (
            "Microsoft develops and licenses software, services, and hardware including "
            "Windows, Microsoft 365, Azure cloud, and LinkedIn."
        ),
    },
    "NFLX": {
        "name": "Netflix, Inc.",
        "sector": "Communication Services",
        "industry": "Entertainment",
        "description": (
            "Netflix provides subscription streaming entertainment services, offering "
            "TV series, films, and games to members worldwide."
        ),
    },
    "GOOGL": {
        "name": "Alphabet Inc.",
        "sector": "Technology",
        "industry": "Internet Content & Information",
        "description": (
            "Alphabet provides online advertising (Google Search, YouTube), cloud "
            "computing (Google Cloud), and emerging technology businesses."
        ),
    },
    "TSLA": {
        "name": "Tesla, Inc.",
        "sector": "Consumer Cyclical",
        "industry": "Auto Manufacturers",
        "description": (
            "Tesla designs, develops, manufactures, and sells electric vehicles, "
            "energy generation and storage systems, and related services."
        ),
    },
    "NVDA": {
        "name": "NVIDIA Corporation",
        "sector": "Technology",
        "industry": "Semiconductors",
        "description": (
            "NVIDIA provides graphics processing units and system-on-chip units for "
            "gaming, data centres, professional visualisation, and automotive markets."
        ),
    },
    "JPM": {
        "name": "JPMorgan Chase & Co.",
        "sector": "Financial Services",
        "industry": "Banks - Diversified",
        "description": (
            "JPMorgan Chase is a global financial services firm offering investment "
            "banking, commercial banking, financial transactions, and asset management."
        ),
    },
    "V": {
        "name": "Visa Inc.",
        "sector": "Financial Services",
        "industry": "Credit Services",
        "description": (
            "Visa operates the world's largest retail electronic payments network, "
            "facilitating transactions between consumers, merchants, and banks globally."
        ),
    },
}

# OHLCV columns to keep when returning history data
_OHLCV = ["Open", "High", "Low", "Close", "Adj Close", "Volume"]


def _safe_float(val) -> float | None:
    """Return float or None; maps NaN and non-numeric values to None."""
    if val is None:
        return None
    try:
        f = float(val)
        return None if np.isnan(f) else f
    except (TypeError, ValueError):
        return None


def load_history(ticker: str) -> pd.DataFrame:
    """
    Load OHLCV history for *ticker*.

    Tries cache/{ticker}_enriched.csv first (returns only the OHLCV columns
    so the chart and backtest code sees a consistent DataFrame).
    Falls back to cache/{ticker}_hist.csv.
    Returns an empty DataFrame when neither file exists.
    """
    for suffix in ("_enriched", "_hist"):
        path = CACHE_DIR / f"{ticker}{suffix}.csv"
        if not path.exists():
            continue
        try:
            df = pd.read_csv(path, index_col="Date", parse_dates=True)
            if df.empty:
                continue
            cols = [c for c in _OHLCV if c in df.columns]
            if "Close" not in cols:
                continue
            return df[cols]
        except Exception:
            continue
    return pd.DataFrame()


def compute_fundamentals(ticker: str) -> dict | None:
    """
    Build the same fundamentals dict that fetch_fundamentals() in app.py
    returns, sourced from the local cache.

    If cache/{ticker}_enriched.csv exists the ten financial metrics are read
    directly from it.  Otherwise only price and category can be derived from
    the raw OHLCV data; all other fields are None (→ N/A in the UI).

    Returns None when the ticker has no cache file at all.
    """
    meta = _META.get(ticker, {})

    # ── Try enriched CSV first ────────────────────────────────────────────────
    enriched_path = CACHE_DIR / f"{ticker}_enriched.csv"
    if enriched_path.exists():
        try:
            df = pd.read_csv(enriched_path, index_col="Date", parse_dates=True)
            if not df.empty and "Close" in df.columns:
                row = df.iloc[-1]   # metric columns are constant; read last row

                pe         = _safe_float(row.get("PE_Ratio"))
                eps_growth = _safe_float(row.get("EPS_Growth"))
                peg        = _safe_float(row.get("PEG_Ratio"))
                # ROE and Dividend_Yield stored as %; app.py expects decimal
                roe_raw    = _safe_float(row.get("ROE"))
                div_raw    = _safe_float(row.get("Dividend_Yield"))
                de         = _safe_float(row.get("Debt_Equity"))
                ps         = _safe_float(row.get("PS_Ratio"))
                cr         = _safe_float(row.get("Current_Ratio"))
                ins_raw    = _safe_float(row.get("Insider_Ownership"))
                price      = _safe_float(row.get("Price")) or _safe_float(
                    df["Close"].dropna().iloc[-1]
                )

                # Lynch growth category from actual EPS growth when available
                def _classify(g):
                    if g is None:
                        return "Unknown", "#8899aa"
                    if g < 5:   return "Slow Grower",    "#8899aa"
                    if g < 15:  return "Stalwart",        "#2d9cdb"
                    if g >= 20: return "Fast Grower 🚀",  "#27ae60"
                    return "Moderate Grower", "#f0c040"

                category, cat_color = _classify(eps_growth)

                return {
                    "name":           meta.get("name", ticker),
                    "sector":         meta.get("sector", "N/A"),
                    "industry":       meta.get("industry", "N/A"),
                    "description":    meta.get("description", ""),
                    "price":          price,
                    "pe":             pe,
                    "eps_growth":     eps_growth,
                    "revenue_growth": None,
                    "peg":            peg,
                    "market_cap":     "N/A",
                    "debt_equity":    de,
                    # app.py displays roe and dividend as decimals (* 100 for %)
                    "roe":            roe_raw / 100 if roe_raw is not None else None,
                    "dividend":       div_raw / 100 if div_raw is not None else None,
                    "cash_per_share": None,
                    "fcf":            None,
                    "ps_ratio":       ps,
                    "current_ratio":  cr,
                    "inst_own":       None,
                    "insider_own":    ins_raw / 100 if ins_raw is not None else None,
                    "category":       category,
                    "cat_color":      cat_color,
                    "from_cache":     True,
                }
        except Exception:
            pass   # fall through to raw-OHLCV path

    # ── Fall back to raw OHLCV (price + category only) ────────────────────────
    hist = load_history(ticker)
    if hist.empty or "Close" not in hist.columns:
        return None

    close = hist["Close"].dropna().astype(float)
    price = float(close.iloc[-1])

    def _ann_return(n: int) -> float | None:
        if len(close) < n + 1:
            return None
        start = float(close.iloc[-n])
        return None if start <= 0 else ((price / start) ** (252 / n) - 1) * 100

    ret_1y = _ann_return(252)

    if ret_1y is None:      category, cat_color = "Unknown",         "#8899aa"
    elif ret_1y < 5:        category, cat_color = "Slow Grower",     "#8899aa"
    elif ret_1y < 15:       category, cat_color = "Stalwart",        "#2d9cdb"
    elif ret_1y >= 20:      category, cat_color = "Fast Grower 🚀",  "#27ae60"
    else:                   category, cat_color = "Moderate Grower", "#f0c040"

    return {
        "name":           meta.get("name", ticker),
        "sector":         meta.get("sector", "N/A"),
        "industry":       meta.get("industry", "N/A"),
        "description":    meta.get("description", ""),
        "price":          price,
        "pe":             None,
        "eps_growth":     None,
        "revenue_growth": None,
        "peg":            None,
        "market_cap":     "N/A",
        "debt_equity":    None,
        "roe":            None,
        "dividend":       None,
        "cash_per_share": None,
        "fcf":            None,
        "ps_ratio":       None,
        "current_ratio":  None,
        "inst_own":       None,
        "insider_own":    None,
        "category":       category,
        "cat_color":      cat_color,
        "from_cache":     True,
    }
